#%RAML 1.0 DataType
type: object
displayName: Job Object
description: Job object dataType

properties:
  customerFormId?: 
    type: string | nil
    required: false
    description: form
  projectName?: 
    type: string | nil
    required: false
    description: project name
  projectStatusInternalId?: 
    type: string | nil
    required: false
    description: status of proj
  nsCustomerInternalId?: 
    type: string | nil
    required: false
    description: customer internal id   
  nsPrimaryCurrencyInternalId?: 
    type: string | nil
    required: false
    description: currency
  projectStartDate?: 
    type: string | nil
    required: false
    description: start date of project   
  nsSubsidiaryInternalId?: 
    type: string | nil
    required: false
    description: subsidiary Int ID
  id?: 
    type: string | nil
    required: false
    description: id
  sfdcOriginalOpportunityNumber?: 
    type: string | nil
    required: false
    description: Original Opty Number
  sfdcOpportunityStage?: 
    type: string | nil
    required: false
    description: opty stage 
  sfdcOpportunityCloseDate?: 
    type: string | nil
    required: false
    description: close date of opty
  sfdcOpportunityCategoryInternalId?: 
    type: string | nil
    required: false
    description: opty category   
  projectRegionInternalId?: 
    type: string | nil
    required: false
    description: region
  projectHierarchyNodeId: 
    type: string | nil
    required: false
    description: Hierrachy Node   
  nsProjectDirectorInternalId?: 
    type: string | nil
    required: false
    description: Director Int ID
  projectCategoryInternalId?: 
    type: string | nil
    required: false
    description: project cat ID
  projectProductInternalId?: 
    type: string | nil
    required: false
    description: product int id
  nsProjectOwnerInternalId?: 
    type: string | nil
    required: false
    description: owner Int Id
  opportunityNumber?: 
    type: string | nil
    required: false
    description: opportunity Number
  gscProjectManagerInternalId?: 
    type: string | nil
    required: false
    description: gsc Int id   
  projectCostCentreInternalId?: 
    type: string | nil
    required: false
    description: cost center Id
  clarityProjectId?: 
    type: string | nil
    required: false
    description: clarity ProjectId   
  psTopOpportunity?: 
    type: string | nil
    required: false
    description: ps Top Opportunity
  psForecastProbability?: 
    type: string | nil
    required: false
    description: ps Forecast Probability   
  sfdcOpportunityProbability?: 
    type: string | nil
    required: false
    description: sfdc Opportunity Probability
  exportToOpenAir?: 
    type: string | nil
    required: false
    description: export To OpenAir   
  openAirProjectStageInternalId?: 
    type: string | nil
    required: false
    description: open Air Project Stage Int Id
  oaProjectTemplateInternalId?: 
    type: string | nil
    required: false
    description: OA Project Template Int Id   
  psPracticeNameInternalId?: 
    type: string | nil
    required: false
    description: ps PracticeName Int Id
  psPracticeUniqueCode?: 
    type: string | nil
    required: false
    description: psPracticeUniqueCode   
  nsProjectServiceType?: 
    type: string | nil
    required: false
    description: NS Project Service Type
  
   
   