#%RAML 1.0 NamedExample
{
  "nsPrimaryCurrencyInternalId": "4",
  "projectStartDate": "2013-05-30",
  "sfdcOpportunityCloseDate": "2013-05-31",
  "sfdcOpportunityCategoryInternalId": "6",
  "nsProjectOwnerInternalId": null,
  "psTopOpportunity": "false",
  "type": "NS_Project__c",
  "projectStatusInternalId": "2",
  "projectCostCentreInternalId": "61",
  "nsCustomerInternalId": "41484",
  "projectProductInternalId": "24",
  "opportunityNumber": null,
  "projectCategoryInternalId": null,
  "projectRegionInternalId": "192",
  "oaProjectTemplateInternalId": null,
  "psForecastProbability": null,
  "psPracticeUniqueCode": null,
  "openAirProjectStageInternalId": "17",
  "clarityProjectId": null,
  "projectHierarchyNodeId": null,
  "customerFormId": "57",
  "sfdcOriginalOpportunityNumber": null,
  "nsProjectServiceType": null,
  "sfdcOpportunityStage": "Closed Won",
  "exportToOpenAir": "false",
  "gscProjectManagerInternalId": null,
  "psPracticeNameInternalId": null,
  "projectName": "ILFSO_AprME  ON33117 1059971IT",
  "nsSubsidiaryInternalId": "149",
  "sfdcOpportunityProbability": null,
  "nsProjectDirectorInternalId": null,
  "id": "a3D20000000PlirEAC"
}